[package]
name = "qwx"
version = "0.0.3"
edition = "2024"
description = "Quaternary Walk Extended"
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/kognitara/qwx.git"

[dependencies]
clap = "4.6.6"
clap_complete = "4.6.9"
crossterm = "0.29.0"
git2 = { version = "0.21.0", features = ["https", "ssh"] }
ignore = "0.4.31"
indicatif = "0.18.6"
inquire = "0.9.4"
num_cpus = "1.17.0"
regex = "1.13.1"
reqwest = { version = "0.13.4", features = ["blocking", "json", "form"] }
ropey = "1.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tree-sitter = { version = "0.26.11", features = ["bindgen"] }
tree-sitter-ada = "0.1.0"
tree-sitter-agda = "1.3.3"
tree-sitter-asm = "0.24.0"
tree-sitter-bash = "0.25.1"
tree-sitter-batch = "0.11.1"
tree-sitter-c = "0.24.2"
tree-sitter-c-sharp = "0.23.5"
tree-sitter-cmake = "0.7.4"
tree-sitter-cpp = "0.23.4"
tree-sitter-css = "0.25.0"
tree-sitter-d = "0.8.2"
tree-sitter-dart = "0.2.0"
tree-sitter-diff = "0.1.0"
tree-sitter-elixir = "0.3.5"
tree-sitter-elm = "5.9.4"
tree-sitter-erlang = "0.20.0"
tree-sitter-fish = "3.6.0"
tree-sitter-fsharp = "0.3.3"
tree-sitter-glsl = "0.2.0"
tree-sitter-go = "0.25.0"
tree-sitter-graphql = "0.2.0"
tree-sitter-haskell = "0.23.1"
tree-sitter-hcl = "1.1.0"
tree-sitter-highlight = "0.26.11"
tree-sitter-hlsl = "0.2.0"
tree-sitter-html = "0.23.2"
tree-sitter-ini = "1.4.0"
tree-sitter-java = "0.23.5"
tree-sitter-javascript = "0.25.0"
tree-sitter-jinja2 = "0.0.16"
tree-sitter-json = "0.24.8"
tree-sitter-kconfig = "1.3.0"
tree-sitter-lua = "0.5.0"
tree-sitter-make = "1.1.1"
tree-sitter-md = { version = "0.5.3", features = ["parser"] }
tree-sitter-nginx = "1.0.1"
tree-sitter-nix = "0.3.0"
tree-sitter-objc = "3.0.2"
tree-sitter-odin = "1.3.0"
tree-sitter-perl = "1.1.2"
tree-sitter-php = "0.24.2"
tree-sitter-powershell = "0.26.4"
tree-sitter-python = "0.25.0"
tree-sitter-r = "1.3.0"
tree-sitter-ruby = "0.23.1"
tree-sitter-rust = "0.24.2"
tree-sitter-sas = "0.4.2"
tree-sitter-scala = "0.26.0"
tree-sitter-swift = "0.7.3"
tree-sitter-typescript = "0.23.2"
tree-sitter-vhdl = "1.4.0"
tree-sitter-xml = "0.7.0"
tree-sitter-yaml = "0.7.2"
tree-sitter-zig = "1.1.2"
tree-sitter-zsh = "0.63.4"
unicode-width = "0.2.2"
walkdir = "2.5.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
