decrease_view = "C--"
increase_view = "C-+"
decrease_workspace = "A--"
increase_workspace = "A-+"
pageup = "pageup"
pagedown = "pagedown"
# --- Navigation type AZERTY ---
move_up = "z"
move_left = "q"
move_down = "s"
move_right = "d"

# --- Édition ---
select_line = "x"
delete_line = "C-x"      # Changé de "d" pour éviter le conflit avec move_right
redo = "r"
undo = "u"
yank = "y"
paste = "p"
delete_selection = "A-d"
save_document = "C-w"    # Changé de "C-s" pour éviter le conflit avec les panneaux

# --- Interface & Panneaux ---
go_top_panel = "C-z"
go_left_panel = "C-q"
go_bottom_panel = "C-s"
go_right_panel = "C-d"

toggle_facet = "A-x"
show_front_facet = "F-1" # Attribué pour éviter le bug de la chaîne vide
show_back_facet = "F-2"  # Attribué pour éviter le bug de la chaîne vide

rotate_clockwise = "A-space"
rotate_counter_clockwise = "C-space"

# --- Déplacements globaux ---
go_top = "A-t"
go_end = "A-e"

# --- Outils & Hub ---
open_finder = "A-o"
edit = "e"
edit_new_line = "o"
open_menu = "A-p"
search = "/"
open_web = "A-w"
open_player = "A-m"

# --- Système ---
exit_mode = "esc"
quit = "F-12"